services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
