# Generated by Django 6.0.8 on 2026-08-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('project_type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('message', models.TextField(verbose_name='需求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '联系留言',
                'verbose_name_plural': '联系留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
