# Generated by Django 6.0.8 on 2026-08-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contract',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contract',
        ),
    ]
