# Generated by Django 6.0.8 on 2026-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contactmessage_contract_alter_contract_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('upcoming', '赛程预告'), ('result', '近期赛果'), ('champion', '冠军榜')], default='upcoming', max_length=20, verbose_name='数据类型')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='日期')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='时间')),
                ('event', models.CharField(max_length=200, verbose_name='赛事')),
                ('stage', models.CharField(blank=True, max_length=200, verbose_name='阶段')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('watch', models.CharField(blank=True, max_length=300, verbose_name='看点')),
                ('player_a', models.CharField(blank=True, max_length=100, verbose_name='对阵 A')),
                ('player_b', models.CharField(blank=True, max_length=100, verbose_name='对阵 B')),
                ('score', models.CharField(blank=True, max_length=100, verbose_name='比分')),
                ('result', models.CharField(blank=True, max_length=200, verbose_name='结果')),
                ('champion', models.CharField(blank=True, max_length=200, verbose_name='冠军')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '比赛赛程',
                'verbose_name_plural': '比赛赛程',
                'db_table': 'match_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(blank=True, default='资讯', max_length=50, verbose_name='分类')),
                ('date', models.CharField(blank=True, max_length=50, verbose_name='日期')),
                ('excerpt', models.TextField(blank=True, verbose_name='摘要')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='图片')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
                'db_table': 'news_article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('en_name', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='协会')),
                ('birth', models.CharField(blank=True, max_length=50, verbose_name='出生日期')),
                ('height', models.CharField(blank=True, max_length=50, verbose_name='身高')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='当前状态')),
                ('style', models.CharField(blank=True, max_length=300, verbose_name='技术特点')),
                ('bio', models.TextField(blank=True, verbose_name='档案介绍')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='图片')),
                ('video', models.CharField(blank=True, max_length=500, verbose_name='视频')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '球员档案',
                'verbose_name_plural': '球员档案',
                'db_table': 'player_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('desc', models.TextField(blank=True, verbose_name='说明')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='图片')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='排名')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='评分')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '装备产品',
                'verbose_name_plural': '装备产品',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
        ),
    ]
