# Generated by Django 6.0.8 on 2026-08-06 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matchschedule_newsarticle_playerprofile_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', '手机'), ('email', '邮箱')], max_length=10, verbose_name='发送渠道')),
                ('account', models.CharField(max_length=120, verbose_name='手机号或邮箱')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('purpose', models.CharField(default='register', max_length=20, verbose_name='用途')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'db_table': 'verification_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='手机已验证')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会员档案',
                'verbose_name_plural': '会员档案',
                'db_table': 'member_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
