# Generated by Django 6.0.8 on 2026-08-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_verificationcode_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('category', models.CharField(choices=[('球迷投稿', '球迷投稿'), ('赛事讨论', '赛事讨论'), ('装备交流', '装备交流'), ('训练心得', '训练心得'), ('其他', '其他')], default='球迷投稿', max_length=50, verbose_name='分类')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('hot_score', models.PositiveIntegerField(default=0, verbose_name='热度值')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '社区投稿',
                'verbose_name_plural': '社区投稿',
                'db_table': 'community_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
